#!/bin/bash
cp -r /opt/afad-wifiautoconfig/afad-wifiautoconfig.sh /usr/bin/
chown root:root /usr/bin/afad-wifiautoconfig.sh
chmod 700 /usr/bin/afad-wifiautoconfig.sh
cp -r /opt/afad-wifiautoconfig/afad-wifiautoconfig.desktop /etc/xdg/autostart/
############ Normal kullanıcılara Wifi Çalıştırma yetkisi ############################
sudoers_file1=$(less /etc/sudoers |grep "NOPASSWD: afad-wifiautoconfig" | wc -l)
if [ "$sudoers_file1" -lt "1" ] ; then
echo 'ALL ALL= NOPASSWD: /usr/bin/afad-wifiautoconfig.sh' | sudo EDITOR='tee -a' visudo
else 
echo sudoers-ok
fi
